// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PrijemZeSkladuFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Příjem ze skladu.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("cs-CZ"), "Příjem ze skladu", "Jako skladník chci přijímat nové nářadí z hlavního skladu na výdejnu", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Příjem ze skladu")))
            {
                AcceptanceTests.PrijemZeSkladuFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "Rozměr",
                        "Druh"});
            table1.AddRow(new string[] {
                        "3-26-006",
                        "TCMT1102xx",
                        "Držák plátku"});
            table1.AddRow(new string[] {
                        "4-41-073",
                        "průměr 25/5,8",
                        "Opěrka hlavy"});
#line 5
 testRunner.Given("seznam nářadí tvoří:", ((string)(null)), table1, "Pokud ");
#line 9
 testRunner.And("nebyly provedeny žádné operace", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "A ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Příjem nového nářadí s vyplněnými všemi hodnotami")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Příjem ze skladu")]
        public virtual void PrijemNovehoNaradiSVyplnenymiVsemiHodnotami()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Příjem nového nářadí s vyplněnými všemi hodnotami", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table2.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table2.AddRow(new string[] {
                        "Počet",
                        "5"});
            table2.AddRow(new string[] {
                        "Cena",
                        "3480.00"});
            table2.AddRow(new string[] {
                        "Dodavatel",
                        "VNP s.r.o."});
#line 12
 testRunner.When("přijímám nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table2, "Když ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table3.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table3.AddRow(new string[] {
                        "Počet",
                        "5"});
            table3.AddRow(new string[] {
                        "Cena",
                        "3480.00"});
            table3.AddRow(new string[] {
                        "Dodavatel",
                        "VNP s.r.o."});
#line 18
 testRunner.Then("je přijato nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table3, "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Dodavatele není nutné vyplňovat")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Příjem ze skladu")]
        public virtual void DodavateleNeniNutneVyplnovat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Dodavatele není nutné vyplňovat", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table4.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table4.AddRow(new string[] {
                        "Počet",
                        "5"});
            table4.AddRow(new string[] {
                        "Cena",
                        "3480.00"});
            table4.AddRow(new string[] {
                        "Dodavatel",
                        ""});
#line 26
 testRunner.When("přijímám nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table4, "Když ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table5.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table5.AddRow(new string[] {
                        "Počet",
                        "5"});
            table5.AddRow(new string[] {
                        "Cena",
                        "3480.00"});
            table5.AddRow(new string[] {
                        "Dodavatel",
                        ""});
#line 32
 testRunner.Then("je přijato nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table5, "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cena musí být nezáporná")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Příjem ze skladu")]
        public virtual void CenaMusiBytNezaporna()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cena musí být nezáporná", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Cena",
                        "-480.00"});
#line 40
 testRunner.When("přijímám nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table6, "Když ");
#line 42
 testRunner.Then("dostanu varování, že cena nesmí být záporná", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Množství musí být kladné")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Příjem ze skladu")]
        public virtual void MnozstviMusiBytKladne()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Množství musí být kladné", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Počet",
                        "0"});
#line 45
 testRunner.When("přijímám nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table7, "Když ");
#line 47
 testRunner.Then("dostanu varování, že množství musí být kladné", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Není možné přijímat nářadí, které není v seznamu používaného nářadí:")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Příjem ze skladu")]
        public virtual void NeniMoznePrijimatNaradiKtereNeniVSeznamuPouzivanehoNaradi()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Není možné přijímat nářadí, které není v seznamu používaného nářadí:", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-018"});
            table8.AddRow(new string[] {
                        "Rozměr",
                        "WAISSER"});
#line 50
 testRunner.When("přijímám nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table8, "Když ");
#line 53
 testRunner.Then("dostanu varování, že není možné přijímat nářadí, které není v seznamu", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
