// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class SeznamNaradiFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Seznam nářadí.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("cs-CZ"), "Seznam nářadí", "Jako správce skladu\tchci mít k dispozici seznam používaného nářadí", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Seznam nářadí")))
            {
                AcceptanceTests.SeznamNaradiFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Každé nářadí je určeno pomocí trojice: výkres, rozměr a druh")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Seznam nářadí")]
        public virtual void KazdeNaradiJeUrcenoPomociTrojiceVykresRozmerADruh()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Každé nářadí je určeno pomocí trojice: výkres, rozměr a druh", ((string[])(null)));
#line 4
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "Rozměr",
                        "Druh"});
            table9.AddRow(new string[] {
                        "3-26-006",
                        "TCMT1102xx",
                        "Držák plátku"});
            table9.AddRow(new string[] {
                        "4-41-073",
                        "průměr 25/5,8",
                        "Opěrka hlavy"});
#line 5
 testRunner.Given("seznam nářadí tvoří:", ((string)(null)), table9, "Pokud ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "Rozměr",
                        "Druh"});
            table10.AddRow(new string[] {
                        "3-26-006",
                        "TCMT1102xx",
                        "Držák plátku"});
            table10.AddRow(new string[] {
                        "4-41-073",
                        "průměr 25/5,8",
                        "Opěrka hlavy"});
#line 9
 testRunner.Then("seznam používaného nářadí obsahuje přesně tuto tabulku:", ((string)(null)), table10, "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Seznam používaného nářadí je seřazen podle výkresu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Seznam nářadí")]
        public virtual void SeznamPouzivanehoNaradiJeSerazenPodleVykresu()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Seznam používaného nářadí je seřazen podle výkresu", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "Rozměr",
                        "Druh"});
            table11.AddRow(new string[] {
                        "3-26-006",
                        "TCMT1102xx",
                        "Držák plátku"});
            table11.AddRow(new string[] {
                        "4-41-073",
                        "průměr 25/5,8",
                        "Opěrka hlavy"});
#line 15
 testRunner.Given("seznam nářadí tvoří:", ((string)(null)), table11, "Pokud ");
#line 19
 testRunner.Then("je nářadí s výkresem 3-26-006 zobrazeno v seznamu používaného nářadí dříve než ná" +
                    "řadí s výkresem 4-41-073.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Seznam používaného nářadí neobsahuje smazané nářadí")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Seznam nářadí")]
        public virtual void SeznamPouzivanehoNaradiNeobsahujeSmazaneNaradi()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Seznam používaného nářadí neobsahuje smazané nářadí", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "Rozměr",
                        "Druh"});
            table12.AddRow(new string[] {
                        "3-26-006",
                        "TCMT1102xx",
                        "Držák plátku"});
            table12.AddRow(new string[] {
                        "4-41-073",
                        "průměr 25/5,8",
                        "Opěrka hlavy"});
#line 22
 testRunner.Given("seznam nářadí tvoří:", ((string)(null)), table12, "Pokud ");
#line 26
 testRunner.And("nářadí s výkresem 3-26-006 bylo smazáno", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "A ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "Rozměr",
                        "Druh"});
            table13.AddRow(new string[] {
                        "4-41-073",
                        "průměr 25/5,8",
                        "Opěrka hlavy"});
#line 27
 testRunner.Then("seznam používaného nářadí obsahuje přesně tuto tabulku:", ((string)(null)), table13, "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
