// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AcceptanceTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class VydejDoVyrobyFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Výdej do výroby.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("cs-CZ"), "Výdej do výroby", "Jako skladník chci vydávat nářadí na pracoviště výroby", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Výdej do výroby")))
            {
                AcceptanceTests.VydejDoVyrobyFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "Rozměr",
                        "Druh"});
            table24.AddRow(new string[] {
                        "3-26-006",
                        "TCMT1102xx",
                        "Držák plátku"});
            table24.AddRow(new string[] {
                        "4-41-073",
                        "průměr 25/5,8",
                        "Opěrka hlavy"});
#line 5
 testRunner.Given("seznam nářadí tvoří:", ((string)(null)), table24, "Pokud ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table25.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table25.AddRow(new string[] {
                        "Počet",
                        "5"});
            table25.AddRow(new string[] {
                        "Cena",
                        "3480.00"});
            table25.AddRow(new string[] {
                        "Dodavatel",
                        "VNP s.r.o."});
#line 9
 testRunner.And("bylo přijato nové nářadí na výdejnu ze skladu s hodnotami:", ((string)(null)), table25, "A ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Výdej na pracoviště výroby")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Výdej do výroby")]
        public virtual void VydejNaPracovisteVyroby()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Výdej na pracoviště výroby", ((string[])(null)));
#line 16
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table26.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table26.AddRow(new string[] {
                        "Počet",
                        "3"});
            table26.AddRow(new string[] {
                        "Pracoviště",
                        "11045330"});
#line 17
 testRunner.When("vydávám nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table26, "Když ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table27.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table27.AddRow(new string[] {
                        "Počet",
                        "3"});
            table27.AddRow(new string[] {
                        "Pracoviště",
                        "11045330"});
#line 22
 testRunner.Then("je vydáno nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table27, "Pak ");
#line 27
 testRunner.And("na výdejně zbývají pro výdej na pracovitě 2 kusy nářadí s výkresem 3-26-006", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "A ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Stejné nářadí je možné vydávat na různá pracovitě, pokud je ještě co vydávat")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Výdej do výroby")]
        public virtual void StejneNaradiJeMozneVydavatNaRuznaPracovitePokudJeJesteCoVydavat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Stejné nářadí je možné vydávat na různá pracovitě, pokud je ještě co vydávat", ((string[])(null)));
#line 29
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table28.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table28.AddRow(new string[] {
                        "Počet",
                        "3"});
            table28.AddRow(new string[] {
                        "Pracoviště",
                        "11045330"});
#line 30
 testRunner.Then("bylo vydáno nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table28, "Pak ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table29.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table29.AddRow(new string[] {
                        "Počet",
                        "2"});
            table29.AddRow(new string[] {
                        "Pracoviště",
                        "54871320"});
#line 35
 testRunner.When("vydávám nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table29, "Když ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table30.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table30.AddRow(new string[] {
                        "Počet",
                        "2"});
            table30.AddRow(new string[] {
                        "Pracoviště",
                        "54871320"});
#line 40
 testRunner.Then("je vydáno nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table30, "Pak ");
#line 45
 testRunner.And("na výdejně zbývá pro výdej na pracovitě 0 kusů nářadí s výkresem 3-26-006", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "A ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Nelze vydávat více kusů, než je k dispozici")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Výdej do výroby")]
        public virtual void NelzeVydavatViceKusuNezJeKDispozici()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Nelze vydávat více kusů, než je k dispozici", ((string[])(null)));
#line 47
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table31.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table31.AddRow(new string[] {
                        "Počet",
                        "3"});
            table31.AddRow(new string[] {
                        "Pracoviště",
                        "11045330"});
#line 48
 testRunner.Then("bylo vydáno nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table31, "Pak ");
#line hidden
            TechTalk.SpecFlow.Table table32 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table32.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table32.AddRow(new string[] {
                        "Počet",
                        "4"});
            table32.AddRow(new string[] {
                        "Pracoviště",
                        "54871320"});
#line 53
 testRunner.When("vydávám nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table32, "Když ");
#line 58
 testRunner.Then("dostanu varování, že nelze vydávat více kusů, než je k dispozici", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pracoviště je nutné zadávat")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Výdej do výroby")]
        public virtual void PracovisteJeNutneZadavat()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Pracoviště je nutné zadávat", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table33 = new TechTalk.SpecFlow.Table(new string[] {
                        "Výkres",
                        "3-26-006"});
            table33.AddRow(new string[] {
                        "Rozměr",
                        "TCMT1102xx"});
            table33.AddRow(new string[] {
                        "Počet",
                        "4"});
            table33.AddRow(new string[] {
                        "Pracoviště",
                        ""});
#line 61
 testRunner.When("vydávám nářadí na pracoviště výroby s hodnotami:", ((string)(null)), table33, "Když ");
#line 66
 testRunner.Then("dostanu varování, že je nutné specifikovat pracoviště, kam se nářadí vydává", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Pak ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
